dist: focal

git:
  depth: false

os: linux
language: generic

services:
  - docker
  
arch:
  - amd64
  - arm64  

before_install:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
  - docker build -t moussavdb/build-java-native-$TRAVIS_CPU_ARCH:latest --build-arg CI_ARCH=$TRAVIS_CPU_ARCH .
script:
  - docker images moussavdb/build-java-native-$TRAVIS_CPU_ARCH
  
after_success:
  - docker push moussavdb/build-java-native-$TRAVIS_CPU_ARCH:latest;
