language: generic

git:
  depth: false

os: linux
dist: jammy

before_install:
  - docker build -t moussavdb/build-java-native:latest .
script:
  - docker images moussavdb/build-java-native
  
after_success:
  - docker login -u="moussavdb" -p="$DOCKER_PASSWORD";
    docker push moussavdb/build-java-native:latest;
